services:
  loglensbackend:
    container_name: loglensbackend
    image: ${DESKTOP_PLUGIN_IMAGE}
    depends_on:
      - loglensdb
  
  loglensdb:
    container_name: loglensdb
    image: mongo:6-jammy
    command: mongod --port 27001
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    #   - MONGO_INITDB_DATABASE=mydb
    ports:
      - '27001:27001'
