services:
  loglensbackend:
    container_name: loglensbackend
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
    depends_on:
      - loglensdb
  
  loglensdb:
    container_name: loglensdb
    image: mongo:6-jammy
    command: mongod --port 27001
    ports:
      - '27001:27001'
